
insert into testivm.customers (customer_name, customer_fav_colour) values ("Naomi", "Orange");
insert into testivm.customers (customer_name, customer_fav_colour) values ("Joshua", "Red");
insert into testivm.customers (customer_name, customer_fav_colour) values ("Iona", "Pink");
insert into testivm.customers (customer_name, customer_fav_colour) values ("Isha", "Purple");
insert into testivm.customers (customer_name, customer_fav_colour) values ("Jacqueline", "Green");
insert into testivm.customers (customer_name, customer_fav_colour) values ("Joseph", "Black");
insert into testivm.items(item_name, item_price) values("Book", "3.93");
insert into testivm.items(item_name, item_price) values("Shampoo", "4.49");
insert into testivm.items(item_name, item_price) values("Mobile Phone", "499.00");
insert into testivm.items(item_name, item_price) values("MacbookPro", "2229.03");
insert into testivm.items(item_name, item_price) values("Bottle of Water", "0.49");
insert into testivm.items(item_name, item_price) values("Chocolate bar", ".89");
insert into testivm.items(item_name, item_price) values("Weekend Festival Ticket", "199.99");
insert into testivm.items(item_name, item_price) values("Gold Earrings", "39.99");
insert into testivm.items(item_name, item_price) values("Gym/Yoga Pass", "48.00");
insert into testivm.items(item_name, item_price) values("Perfume", "29.99");
insert into testivm.orders (fk_customer_id) values (1);
insert into testivm.orders (fk_customer_id) values (2);
insert into testivm.orders (fk_customer_id) values (3);
insert into testivm.orders (fk_customer_id) values (4);
insert into testivm.orders (fk_customer_id) values (5);
insert into testivm.orders (fk_customer_id) values (6);
insert into testivm.orderline(fk_order_id, fk_item_id, quantity_ordered) values (1, 7, 5);
insert into testivm.orderline(fk_order_id, fk_item_id, quantity_ordered) values (2, 9, 3);
insert into testivm.orderline(fk_order_id, fk_item_id, quantity_ordered) values (2, 17, 2);
insert into testivm.orderline(fk_order_id, fk_item_id, quantity_ordered) values (3, 7, 5);
insert into testivm.orderline(fk_order_id, fk_item_id, quantity_ordered) values (4, 10, 2);
insert into testivm.orderline(fk_order_id, fk_item_id, quantity_ordered) values (4, 8, 5);
insert into testivm.orderline(fk_order_id, fk_item_id, quantity_ordered) values (2, 9, 3);
insert into testivm.orderline(fk_order_id, fk_item_id, quantity_ordered) values (2, 9, 3);
insert into testivm.orderline(fk_order_id, fk_item_id, quantity_ordered) values (2, 9, 3);
UPDATE orders SET fk_customer_id = 1 WHERE order_id = 1;
update orders set fk_customer_id =1 where order_id = 7;
select * from items;
select * from orderline;
select * from orders;
select order_id, sum(quantity_ordered*item_price) as order_total from orders join orderline on orders.order_id = orderline.fk_order_id join items on items.item_id = orderline.fk_item_id group by order_id;
